### ISSUE TITLE
Replace "developer" links in httpbin?

### ISSUE THREAD

**Issue by mgorny** [psf/httpbin#13]
I've noticed that the main page of httpbin still links to the website and email of Kenneth Reitz. Since they no longer reply on  the topic of the project, perhaps we should replace them? Maybe just replace both with a link to this GitHub repository.

**Comment by kevin1024** [comment]
Works for me.  Maybe there's a way to do that but still thank Kenneth for creating the project on the main page?

**Comment by mgorny** [comment]
Perhaps a copyright footer — something like YEAR-YEAR Kenneth Reitz, YEAR-YEAR httpbin maintainers…

FWICS the GitHub source link needs to be updated too. There's also a docker image, I don't know if you want to publish one or remove that part.

**Comment by mgorny** [comment]
#24 now.
