### ISSUE TITLE
Allow starting the process on a non-provileged port

### ISSUE THREAD

**Issue by exhuma** [psf/httpbin#2]
Currently, port `80` is hard-coded. This is no allowed on some deployment environments (f.ex. OpenShift).

Please provide a way to change that port upon startup. For example using an environment variable.

**Comment by exhuma** [comment]
I'm currently working on a PR but the `docker build` process seems broken. I'll try to get that working and add it into the same branch if that's okay.

**Comment by exhuma** [comment]
Added in PR #4

**Comment by kevin1024** [comment]
Thanks for your contribution! PR has been merged.
