### ISSUE TITLE
Unable to pull or run docker image

### ISSUE THREAD

**Issue by Guts** [psf/httpbin#27]
Running docker commands as  copied from readme:

```sh
> docker run -p 80:8080 ghcr.io/psf/httpbin
Unable to find image 'ghcr.io/psf/httpbin:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/psf/httpbin/manifests/latest": unauthorized.
See 'docker run --help'.
> docker pull ghcr.io/psf/httpbin
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/psf/httpbin/manifests/latest": unauthorized
```

Environment:

Ubuntu 22.04.x up to date

```sh
> docker --version
Docker version 24.0.5, build ced0996
```

**Comment by Smeedy** [comment]
You need to do a `docker login` first using a Personal Access Token. See this [page on Github](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

But even so, the pull itself will give a denied so I think there's something on the permissions with this particular image which the author needs to fix since I am able to pull other public images from ghcr.io.

```
$ echo $CR_PAT | docker login ghcr.io -u smeedy --password-stdin
Login Succeeded
$ docker pull ghcr.io/psf/httpbin

Using default tag: latest
Error response from daemon: denied
```

**Comment by Guts** [comment]
Thanks @Smeedy.

So the image is not meant to be publicly used without authentication (quota)?

**Comment by edsu** [comment]
I'm seeing `Error response from daemon: denied` after having logged in with a token:

```bash
$ docker login ghcr.io -u edsu
$ docker pull ghcr.io/psf/httpbin
Using default tag: latest
Error response from daemon: denied
```

**Comment by exhuma** [comment]
@kevin1024 The image is currently not available publicly on ghcr.io. Can something be done with the permissions of the registry? If not, we may need to shift back to docker-hub.

**Comment by exhuma** [comment]
> Thanks @Smeedy.
> 
> So the image is not meant to be publicly used without authentication (quota)?

I don't think it's intentional. The deployment/publishing procedure was recently updated with increased automation. As we currently can't push to the original "Kenneth Reitz" namespace we shifted over to ghcr.io.  We may need to revise that decision if ghcr.io turns out to be problematic for public hosting.

Note: I am *not* a maintainer of the project but I *am* the author of the PR which is responsible for this change.

**Comment by Guts** [comment]
Thanks you for your inputs, that helps to wait 😉.

**Comment by sambercovici** [comment]
Can ghcr support accessing images without authenticating?

**Comment by Guts** [comment]
> Can ghcr support accessing images without authenticating?

I'm pretty sure it does. For example, I'm intensively using GDAL images which have been moved from dockerhub to GHCR: https://github.com/OSGeo/gdal/tree/master/docker

**Comment by sambercovici** [comment]
> > Can ghcr support accessing images without authenticating?
> 
> I'm pretty sure it does. For example, I'm intensively using GDAL images which have been moved from dockerhub to GHCR: https://github.com/OSGeo/gdal/tree/master/docker
Great!

What is different here?

**Comment by Guts** [comment]
> What is different here?

Not sure to get your point.  
The difference is the issue's topic: it's not possible to pull (authenticated or not) this repo container package from GHCR.

**Comment by sambercovici** [comment]
I apologize for the briefness.
What I mean is, is it clear why this specific repo is not allowing public access and/or what needs to be changed?

**Comment by exhuma** [comment]
I'm pretty sure it's just an oversight from the migration. I *assume* that it's only a permission setting for the GitHub project. This needs to be done by one of the project owners/admins. Pinging @kevin1024 again ;)

**Comment by simon-weber** [comment]
Any updates on this? Looks like it's still an issue.

**Comment by marcospereira** [comment]
> What is different here?

To point out the documentation here, the package needs to be made public. From [GitHub docs](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#about-setting-visibility-and-access-permissions-for-packages):

> However, in the Container registry, *public packages allow anonymous access and can be pulled without authentication or signing in via the CLI*.

And these are the instructions about how to make it public to anyone: [Configuring visibility of packages for an organization](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-packages-for-an-organization).

There is a [`publish` workflow](https://github.com/psf/httpbin/actions/workflows/publish.yml) that publishes the docker image already. So, it is only a matter of the package's visibility configuration. 

Maybe @sigmavirus24 @nateprewitt have access to do it?

**Comment by sigmavirus24** [comment]
@marcospereira please don't mention people. As a general rule, if I could have fixed this already, I would have. I don't have the ability to configure anything about this repository beyond some very basic features around pull requests.

**Comment by marcospereira** [comment]
Okay, apologize about that. Where would be the appropriate place to discuss it?

Again, sorry about the noise.

**Comment by ewdurbin** [comment]
If the maintainers of this repo are 👍🏼, I'm happy to flip the bit to make the published image public. cc @psf/httpbin

**Comment by nateprewitt** [comment]
I think Kevin was the only one involved with the image, neither Ian or I were involved with the setup for docker. I don't have an issue with making it public, but we may want comment from Kevin first.

**Comment by kevin1024** [comment]
I think we should make it public!

**Comment by ewdurbin** [comment]
It's done!

<img width="570" alt="Screenshot 2024-06-18 at 7 39 01 AM" src="https://github.com/psf/httpbin/assets/1200832/8092e055-ef5f-409a-98ca-fc39374b218f">

**Comment by kevin1024** [comment]
Nice! Thank you.

**Comment by Guts** [comment]
Thanks you!

**Comment by ewdurbin** [comment]
@kevin1024 I opened a PR to address the lack of ARM64 images as well: https://github.com/psf/httpbin/pull/46
