### ISSUE TITLE
Dropping direct dependency "werkzeug" in PR #29 was mistaken

### ISSUE THREAD

**Issue by hartwork** [psf/httpbin#38]
Pull request #29 dropped werkzeug as a direct dependency (probably thinking that flask bringing it in is enough, but through flask it is an _indirect_ dependency while httpbin still imports werkzeug *directly* [in multiple places](https://github.com/search?q=repo%3Apsf%2Fhttpbin+werkzeug&type=code)). Please bring the direct dependency back. If you're with me on this, I can make a pull request. What do you think?

CC @nateprewitt

**Comment by nateprewitt** [comment]
Yep, you're right @hartwork. We should have left that intact, feel free to open a PR to readd it, otherwise I'll fix it tomorrow.

**Comment by hartwork** [comment]
@nateprewitt glad to hear, I have created pull request #39 now for review :beers:
